# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Start Nacos
      run: |
        git clone https://github.com/nacos-group/nacos-docker.git
        cd nacos-docker
        docker-compose -f example/standalone-derby.yaml up -d

#     - name: Build
#       run: go build -v ./...
    
    - name: Start backend servers
      run: cd RPC_Server && chmod +x output/bin/serviceA && sh build.sh && sh output/bootstrap.sh

    - name: Test
      run: go test -v API_Gateway_Server/...
      
    - name: Stop Nacos
      run: |
        cd nacos-docker
        docker-compose -f example/standalone-derby.yaml down
